from setuptools import setup, find_packages

setup(name='subset_nwm_netcdf',
      version='1.1.4',
      description='Subset National Water Model (NWM) NetCDF Ver1.1',
      url='https://github.com/zhiyuli/subset_nwm_netcdf',
      author='Zhiyu/Drew Li',
      author_email='zyli2004@gmail.com',
      license='BSD-2',
      include_package_data=True,
      packages=find_packages('src'),
      package_dir={'': 'src'},
      zip_safe=False,
      # package_data={'': ['*.py'],
      #               'subset_nwm_netcdf': ['static/sed_win/*',
      #                                     'static/data/utah/*',
      #                                     'static/netcdf_templates/v1.1/forcing/analysis_assim/*',
      #                                     'static/netcdf_templates/v1.1/forcing/medium_range/*',
      #                                     'static/netcdf_templates/v1.1/forcing/short_range/*',
      #                                     'static/netcdf_templates/v1.1/forecast/analysis_assim/*',
      #                                     'static/netcdf_templates/v1.1/forecast/short_range/*',
      #                                     'static/netcdf_templates/v1.1/forecast/medium_range/*',
      #                                     'static/netcdf_templates/v1.1/forecast/long_range/*'],
      #               },
      )
